language: swift

before_install:
  - gem install cocoapods
  - pod repo update
  - pod install
  - echo "$auth" > "Convertify/Stores/Auth.swift"
podfile: Podfile
osx_image: xcode11.3
xcode_workspace: Convertify.xcworkspace
xcode_scheme: Convertify
xcode_destination: platform=iOS Simulator,OS=13.2.2,name=iPhone 11 Pro Max
