language: swift

before_install:
  - gem install cocoapods
  - pod repo update
  - pod install
  - echo $auth > "Convertify/Stores/Auth.swift"
podfile: Podfile
osx_image: xcode10
xcode_workspace: Convertify.xcworkspace
xcode_scheme: Convertify
xcode_destination: platform=iOS Simulator,OS=11.4,name=iPad Pro (9.7-inch)
