name: Daily cron test

on:
  schedule:
    - cron: '0 12 * * *'

jobs:
  test:
    name: Test
    runs-on: macos-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=13.2.2,name=iPhone 11']
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Create Auth.swift
        run: echo "${auth}" > "Convertify/Stores/Auth.swift"
        env:
          auth: ${{ secrets.auth }}
      - name: Build and Test
        run: xcodebuild clean test -project Convertify.xcodeproj -scheme Convertify -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        env:
         destination: ${{ matrix.destination }}
